### ISSUE TITLE
emacs --daemon don't start anymore

### ISSUE THREAD

**Issue by bricewge** [Malabarba/beacon#39]
This bug as already been reported on your blog [here](http://endlessparentheses.com/beacon-never-lose-your-cursor-again.html#comment-2333515276).

Calling `emacs --daemon` with `beacon` enabled make the daemon to never start, it get stuck in his initialisation phase without complaining or anything else. So doing `emacs --daemon --debug-int` doesn't work as it never start. 
The solution proposed by @manuel-uberti in the comment's of your blog doesn't work for me.

To reproduce start `emacs --daemon`, connect to it with an `emacsclient`, load `beacon`, evaluate `(beacon-mode 1)`, select another window `C-x o` then it report `Error in post-command-hook (beacon--post-command): (error "Invalid color")`.
Following is the backtrace:
```
Debugger entered--Lisp error: (error "Invalid color")
  color-distance("black" nil)
  beacon--color-range()
  beacon--shine()
  beacon-blink()
  beacon--blink-on-focus()
  run-hooks(focus-in-hook)
  handle-focus-in((focus-in #<frame emacs@noisette 0x670fb68>))
  call-interactively(handle-focus-in nil [(focus-in #<frame emacs@noisette 0x670fb68>)])
  command-execute(handle-focus-in nil [(focus-in #<frame emacs@noisette 0x670fb68>)] t)
  recursive-edit()
  debug(debug)
  debug--implement-debug-on-entry(1)
  apply(debug--implement-debug-on-entry 1)
* other-window(1)
  call-interactively(other-window nil nil)
  command-execute(other-window)
```

**Comment by manuel-uberti** [comment]
My bad, my solution works for me, but I'm not starting Emacs with ```emacs --daemon```. I do it like this:
```
;; The server of `emacsclient'
(use-package server
  :defer t
  ;; Start server only if it is not already running
  :config (unless (server-running-p)
            (server-mode))
  :diminish (server-buffer-clients . " ⓒ"))
```
Sorry for the misunderstanding.

**Comment by bricewge** [comment]
No problem.

For the moment my workaround with `use-package` is to use `:if (not (daemonp))` to not load `beacon` when Emacs is running as a daemon.

**Comment by Malabarba** [comment]
Should be fixed now. Let me know if it works!

**Comment by bricewge** [comment]
It still present. But actually it doesn't come from your mode, but from the use of a dirty [workaround](https://github.com/bbatsov/solarized-emacs/issues/18#issuecomment-31434473) for a long standing bug in the the solarized theme. So I don't think it need to be fixed.

But FYI the error is:
``` emacs-lisp
Unable to load color "nil"
Error in post-command-hook (beacon--post-command): (wrong-type-argument number-or-marker-p nil)
```
And here it the backtrace:
``` emacs-lisp
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  beacon--int-range(32767.5 nil)
  #[257 "\302\303\301\234\300\234\"!\207" [nil (32767.5 32767.5 32767.5) butlast beacon--int-range] 6 "\n\n(fn N)"](0)
  mapcar(#[257 "\302\303\301\234\300\234\"!\207" [nil (32767.5 32767.5 32767.5) butlast beacon--int-range] 6 "\n\n(fn N)"] [0 1 2])
  beacon--color-range()
  beacon--shine()
  beacon-blink()
  beacon--blink-on-focus()
  run-hooks(focus-in-hook)
  handle-focus-in((focus-in #<frame emacs@noisette 0x68cb4d0>))
  call-interactively(handle-focus-in nil [(focus-in #<frame emacs@noisette 0x68cb4d0>)])
  command-execute(handle-focus-in nil [(focus-in #<frame emacs@noisette 0x68cb4d0>)] t)

```

**Comment by Malabarba** [comment]
Pushed another change for this. Let me know if it works

**Comment by bricewge** [comment]
Nope, still not. But I really don't think it's worth going deeper into this issue.

``` emacs-lisp
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  beacon--int-range(32767.5 nil)
  #[257 "\302\303\301\234\300\234\"!\207" [nil (32767.5 32767.5 32767.5) butlast beacon--int-range] 6 "\n\n(fn N)"](0)
  mapcar(#[257 "\302\303\301\234\300\234\"!\207" [nil (32767.5 32767.5 32767.5) butlast beacon--int-range] 6 "\n\n(fn N)"] [0 1 2])
  beacon--color-range()
  beacon--shine()
  beacon-blink()
  beacon--blink-on-focus()
  run-hooks(focus-in-hook)
  handle-focus-in((focus-in #<frame emacs@noisette 0x55528a0>))
  call-interactively(handle-focus-in nil [(focus-in #<frame emacs@noisette 0x55528a0>)])
  command-execute(handle-focus-in nil [(focus-in #<frame emacs@noisette 0x55528a0>)] t)
```
Thanks for trying anyway. (:
